# Generated by Django 5.2.6 on 2025-09-26 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quesiton',
            new_name='Question',
        ),
    ]
